/*
 * imbh.h — C API for IMBH (the embeddable observability database).
 *
 * GENERATED by cbindgen from the imbh-c crate. Do not edit by hand; regenerate with `cargo build`.
 *
 * Query results are handed back as an Arrow C Data Interface `struct ArrowArrayStream`, whose native
 * type comes from Arrow's own <arrow/c/abi.h> (a copy is bundled at include/arrow/c/abi.h; a consumer
 * with Arrow installed picks up theirs). The caller owns the stream and must release it
 * (`stream.release(&stream)`) or hand it to an Arrow importer that takes ownership.
 */

#ifndef IMBH_H
#define IMBH_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include <arrow/c/abi.h>

/**
 * Result code returned by every fallible `imbh_*` function. `0` (`IMBH_ERROR_OK`) is success.
 *
 * The mapping from [`imbh::Error`] checks the stable classifiers first (`is_backpressure` →
 * `BACKPRESSURE`, `is_not_found` → `NOT_FOUND`), then falls back to the top-level category. Two codes
 * originate in the binding itself: `INVALID_ARG` (null pointer / non-UTF-8 input) and `PANIC` (a
 * caught Rust panic).
 */
enum imbh_error
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Success.
     */
    IMBH_ERROR_OK = 0,
    /**
     * A NULL pointer or otherwise invalid argument was passed to the binding.
     */
    IMBH_ERROR_INVALID_ARG = 1,
    /**
     * A Rust panic was caught at the FFI boundary (should not happen; report as a bug).
     */
    IMBH_ERROR_PANIC = 2,
    /**
     * The referenced entity was not found (e.g. unknown table/column). Maps `is_not_found`.
     */
    IMBH_ERROR_NOT_FOUND = 3,
    /**
     * Ingest backpressure: the async-ingest queue is full — retry later. `is_backpressure`.
     */
    IMBH_ERROR_BACKPRESSURE = 4,
    /**
     * DB open / recovery failure (lockfile, corrupt manifest, unsupported WAL frame, open I/O).
     */
    IMBH_ERROR_OPEN = 5,
    /**
     * Ingest failure (OTLP decode, buffer error).
     */
    IMBH_ERROR_INGEST = 6,
    /**
     * Query planning or execution failure.
     */
    IMBH_ERROR_QUERY = 7,
    /**
     * Storage-engine failure (seal, segment I/O, WAL, Parquet, manifest).
     */
    IMBH_ERROR_STORAGE = 8,
    /**
     * Invalid configuration.
     */
    IMBH_ERROR_CONFIG = 9,
    /**
     * The database handle has been closed.
     */
    IMBH_ERROR_CLOSED = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum imbh_error imbh_error;
#else
typedef int32_t imbh_error;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * WAL fsync policy for on-disk databases (`imbh_open_options::wal_mode`).
 */
typedef enum imbh_wal_mode {
    /**
     * Never fsync inline; durability follows the OS.
     */
    IMBH_WAL_MODE_OFF = 0,
    /**
     * Fsync at most every `wal_interval_ms` (0 → 1000ms).
     */
    IMBH_WAL_MODE_INTERVAL = 1,
    /**
     * Fsync every ingest before returning (durable receipts).
     */
    IMBH_WAL_MODE_ALWAYS = 2,
} imbh_wal_mode;

/**
 * Segment compression codec (`imbh_open_options::compression`).
 */
typedef enum imbh_compression {
    IMBH_COMPRESSION_NONE = 0,
    IMBH_COMPRESSION_LZ4 = 1,
    /**
     * Zstd at `zstd_level` (0 → level 3).
     */
    IMBH_COMPRESSION_ZSTD = 2,
} imbh_compression;

/**
 * Read-only snapshot refresh policy (`imbh_open_options::refresh`) — how a reader picks up the
 * writer's newly-sealed segments (mirrors `imbh::Refresh`).
 */
typedef enum imbh_refresh_mode {
    /**
     * Leave IMBH's default policy in place (the zero value — a zeroed options struct changes nothing).
     */
    IMBH_REFRESH_MODE_DEFAULT = 0,
    /**
     * Re-scan the manifest on every query.
     */
    IMBH_REFRESH_MODE_ON_QUERY = 1,
    /**
     * Never auto-refresh; the reader sees a fixed snapshot until reopened.
     */
    IMBH_REFRESH_MODE_MANUAL = 2,
    /**
     * Refresh when the snapshot is older than `refresh_ttl_ms`.
     */
    IMBH_REFRESH_MODE_TTL = 3,
} imbh_refresh_mode;

/**
 * Physical table selector, in IMBH's stable order.
 */
typedef enum imbh_table {
    IMBH_TABLE_LOGS = 0,
    IMBH_TABLE_SPANS = 1,
    IMBH_TABLE_METRICS_GAUGE = 2,
    IMBH_TABLE_METRICS_SUM = 3,
    IMBH_TABLE_METRICS_HISTOGRAM = 4,
    IMBH_TABLE_METRICS_EXP_HISTOGRAM = 5,
    IMBH_TABLE_METRICS_SUMMARY = 6,
} imbh_table;

/**
 * Log scan direction (logs default to newest-first).
 */
typedef enum imbh_direction {
    IMBH_DIRECTION_BACKWARD = 0,
    IMBH_DIRECTION_FORWARD = 1,
} imbh_direction;

/**
 * Numeric-comparison operator for `add_attr_num`.
 */
typedef enum imbh_num_op {
    IMBH_NUM_OP_GT = 0,
    IMBH_NUM_OP_GE = 1,
    IMBH_NUM_OP_LT = 2,
    IMBH_NUM_OP_LE = 3,
} imbh_num_op;

/**
 * The scalar metric family a `imbh_metric_query` targets.
 */
typedef enum imbh_metric_table {
    IMBH_METRIC_TABLE_GAUGE = 0,
    IMBH_METRIC_TABLE_SUM = 1,
} imbh_metric_table;

/**
 * Aggregation applied within each metric series/bucket.
 */
typedef enum imbh_aggregation {
    IMBH_AGGREGATION_SUM = 0,
    IMBH_AGGREGATION_AVG = 1,
    IMBH_AGGREGATION_MIN = 2,
    IMBH_AGGREGATION_MAX = 3,
    IMBH_AGGREGATION_COUNT = 4,
} imbh_aggregation;

/**
 * PromQL-style label operator for `imbh_metric_query_add_filter` (`=`/`!=`/`=~`/`!~`).
 */
typedef enum imbh_label_op {
    IMBH_LABEL_OP_EQ = 0,
    IMBH_LABEL_OP_NE = 1,
    IMBH_LABEL_OP_REGEX = 2,
    IMBH_LABEL_OP_NOT_REGEX = 3,
} imbh_label_op;

/**
 * How a metric range query turns per-bucket samples into a value.
 */
typedef enum imbh_rate_mode {
    IMBH_RATE_MODE_OFF = 0,
    IMBH_RATE_MODE_DELTA = 1,
    IMBH_RATE_MODE_COUNTER = 2,
} imbh_rate_mode;

/**
 * The metric family a `imbh_metric_points_query` (raw, unaggregated samples) targets. Unlike
 * `imbh_metric_table`, this includes `Histogram` (points queries read histogram rows directly).
 */
typedef enum imbh_metric_point_kind {
    IMBH_METRIC_POINT_KIND_GAUGE = 0,
    IMBH_METRIC_POINT_KIND_SUM = 1,
    IMBH_METRIC_POINT_KIND_HISTOGRAM = 2,
} imbh_metric_point_kind;

/**
 * Opaque database handle. Created by `imbh_db_open_memory` / `imbh_db_open`, released by
 * `imbh_db_free`. Not thread-safe for concurrent mutation from multiple threads on the same handle
 * (the underlying `Db` is `Send + Sync`, but this binding drives it on a single owned runtime).
 */
typedef struct imbh_db imbh_db;

/**
 * Opaque builder for a typed log query. Create with `imbh_log_query_new`, free with
 * `imbh_log_query_free`.
 */
typedef struct imbh_log_query imbh_log_query;

/**
 * Opaque builder for a metric-points (raw, unaggregated samples) query. There is no proto message for
 * it, so this stashes the inputs and assembles the native fluent `MetricPointsQuery` when run.
 */
typedef struct imbh_metric_points_query imbh_metric_points_query;

/**
 * Opaque builder for a typed metric range query.
 */
typedef struct imbh_metric_query imbh_metric_query;

/**
 * Opaque builder for a typed span-metrics (RED) query.
 */
typedef struct imbh_span_metrics_query imbh_span_metrics_query;

/**
 * Opaque builder for a trace-search query (backed by the proto `TraceQuery` message, same as the
 * other typed builders). Create with `imbh_trace_query_new`, free with `imbh_trace_query_free`.
 */
typedef struct imbh_trace_query imbh_trace_query;

/**
 * An owned byte buffer handed back across the FFI boundary (e.g. Arrow-IPC stream bytes from
 * `imbh_db_export` / `imbh_db_query_sql_ipc`). The buffer is allocated by the binding; the caller
 * must release it with `imbh_bytes_free` exactly once. `data` may be null iff `len == 0`.
 */
typedef struct imbh_bytes {
    uint8_t *data;
    uintptr_t len;
} imbh_bytes;

/**
 * On-disk open options. Pass `NULL` for defaults (WAL `Interval(1s)`, Zstd(3), read-write). Each
 * field is honoured only for the matching mode (e.g. `wal_interval_ms` only when `wal_mode` is
 * `INTERVAL`). Every numeric field treats `0` as "IMBH default", so a zeroed struct (apart from the
 * two enums, whose `0` variants are also "leave default") is a valid all-defaults request.
 */
typedef struct imbh_open_options {
    enum imbh_wal_mode wal_mode;
    uint64_t wal_interval_ms;
    enum imbh_compression compression;
    int32_t zstd_level;
    bool read_only;
    bool allow_stale_reads;
    /**
     * In-memory buffer cap in bytes (0 → IMBH default, 128 MiB).
     */
    uint64_t memory_budget_bytes;
    /**
     * Drop data older than N days (0 → keep, unless `max_disk_bytes` bounds it).
     */
    uint64_t retention_days;
    /**
     * Bound on-disk segment bytes (0 → unbounded).
     */
    uint64_t max_disk_bytes;
    /**
     * Read-only snapshot refresh policy; `refresh_ttl_ms` applies only when this is `TTL`.
     */
    enum imbh_refresh_mode refresh;
    uint64_t refresh_ttl_ms;
    /**
     * Run background maintenance every N ms on an owned OS thread (0 → manual only).
     */
    uint64_t maintenance_background_ms;
    /**
     * Attribute keys to promote to dedicated columns. `promote_keys` may be null iff
     * `promote_keys_len == 0`.
     */
    const char *const *promote_keys;
    uintptr_t promote_keys_len;
} imbh_open_options;

/**
 * Outcome of an ingest call (mirrors `imbh::IngestReceipt`). On the default inline path `lsn`/
 * `durable` are meaningful and `queued == false`.
 */
typedef struct imbh_ingest_receipt {
    uint64_t accepted;
    uint64_t rejected;
    uint64_t lsn;
    bool durable;
    bool queued;
} imbh_ingest_receipt;

/**
 * Result of `imbh_db_maintain` (mirrors `imbh::MaintenanceReport`).
 */
typedef struct imbh_maintenance_report {
    bool sealed;
    uint64_t segments_dropped;
    uint64_t bytes_freed;
} imbh_maintenance_report;

/**
 * Result of `imbh_db_compact` (mirrors `imbh::CompactionReport`).
 */
typedef struct imbh_compaction_report {
    uint64_t segments_merged;
    uint64_t segments_created;
} imbh_compaction_report;

/**
 * Engine-wide gauges plus cross-table totals (mirrors `imbh::DbStats`). Use `imbh_db_table_stats`
 * for a single table's breakdown.
 */
typedef struct imbh_stats {
    uint64_t buffer_bytes;
    uint64_t wal_bytes;
    uint64_t durable_lsn;
    uint64_t ingest_queue_depth;
    uint64_t ingest_dropped;
    uint64_t ingest_errors;
    uint64_t total_segment_count;
    uint64_t total_segment_rows;
    uint64_t total_buffer_rows;
} imbh_stats;

/**
 * Per-table statistics (mirrors `imbh::TableStats`). `has_time_bounds` is false when the table has no
 * rows, in which case the min/max fields are 0.
 */
typedef struct imbh_table_stats {
    enum imbh_table table;
    uint64_t segment_count;
    uint64_t segment_rows;
    uint64_t buffer_rows;
    int64_t min_time_unix_nano;
    int64_t max_time_unix_nano;
    bool has_time_bounds;
} imbh_table_stats;

/**
 * Result of `imbh_db_snapshot` (mirrors `imbh::SnapshotInfo`). The destination directory is the `dir`
 * the caller passed; `segments` is the number of segment files hard-linked (or copied) into it.
 */
typedef struct imbh_snapshot_info {
    uint64_t segments;
} imbh_snapshot_info;

/**
 * Read-side scan statistics for a typed query (mirrors `imbh::QueryStats`).
 */
typedef struct imbh_query_stats {
    uint64_t segments_scanned;
    uint64_t segments_pruned;
    uint64_t rows_scanned;
    uint64_t rows_returned;
    uint64_t bytes_scanned;
    uint64_t elapsed_ns;
    bool used_index;
} imbh_query_stats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a buffer returned by the binding (`imbh_db_export` / `imbh_db_query_sql_ipc`). Passing a
 * zero-length buffer, or one already freed to a `{null, 0}`, is a no-op.
 *
 * # Safety
 * `buf` must be a buffer returned by this binding and not already freed. Do not free it twice or free
 * a buffer the caller allocated.
 */
void imbh_bytes_free(struct imbh_bytes buf);

/**
 * Open an ephemeral, in-process database (WAL off). Writes `*out` on success.
 *
 * # Safety
 * `out` must be a valid, writable `imbh_db*` slot.
 */
imbh_error imbh_db_open_memory(struct imbh_db **out);

/**
 * Open a durable, on-disk database at `path`. Pass `opts == NULL` for defaults. Writes `*out` on
 * success.
 *
 * # Safety
 * `path` must be a valid C string; `opts` may be null; `out` must be a valid writable slot.
 */
imbh_error imbh_db_open(const char *path,
                        const struct imbh_open_options *opts,
                        struct imbh_db **out);

/**
 * Open an existing on-disk database at `path` **read-only** — no WAL writes, no seal/compaction, and
 * ingest calls fail. A convenience for `imbh_db_open` with `read_only = true`; the natural handle for
 * a query-only reader over another process's database. Writes `*out` on success.
 *
 * # Safety
 * `path` must be a valid C string; `out` a valid, writable `imbh_db*` slot.
 */
imbh_error imbh_db_open_read_only(const char *path,
                                  struct imbh_db **out);

/**
 * Close the database (idempotent): drains any workers and force-seals the buffer. The handle stays
 * valid (subsequent calls return `IMBH_ERROR_CLOSED`) until `imbh_db_free`.
 *
 * # Safety
 * `db` must be a valid handle or null.
 */
imbh_error imbh_db_close(struct imbh_db *db);

/**
 * Close (if still open) and free the handle. After this the pointer is dangling. Passing null is a
 * no-op.
 *
 * # Safety
 * `db` must be a handle returned by `imbh_db_open*` and not already freed, or null.
 */
void imbh_db_free(struct imbh_db *db);

/**
 * Ingest protobuf OTLP `ExportLogsServiceRequest` bytes. Writes `*receipt` if non-null.
 *
 * # Safety
 * `db` a valid handle; `otlp`/`len` a valid byte range (`otlp` may be null iff `len == 0`);
 * `receipt` may be null.
 */
imbh_error imbh_db_ingest_logs(struct imbh_db *db,
                               const uint8_t *otlp,
                               uintptr_t len,
                               struct imbh_ingest_receipt *receipt);

/**
 * Ingest protobuf OTLP `ExportTraceServiceRequest` bytes. Writes `*receipt` if non-null.
 *
 * # Safety
 * `db` a valid handle; `otlp`/`len` a valid byte range (`otlp` may be null iff `len == 0`);
 * `receipt` may be null.
 */
imbh_error imbh_db_ingest_traces(struct imbh_db *db,
                                 const uint8_t *otlp,
                                 uintptr_t len,
                                 struct imbh_ingest_receipt *receipt);

/**
 * Ingest protobuf OTLP `ExportMetricsServiceRequest` bytes. Writes `*receipt` if non-null.
 *
 * # Safety
 * `db` a valid handle; `otlp`/`len` a valid byte range (`otlp` may be null iff `len == 0`);
 * `receipt` may be null.
 */
imbh_error imbh_db_ingest_metrics(struct imbh_db *db,
                                  const uint8_t *otlp,
                                  uintptr_t len,
                                  struct imbh_ingest_receipt *receipt);

/**
 * Run a SQL query over `logs`/`spans`/`metrics_*` (buffer ∪ segments) and export the result into
 * `*out` as an Arrow `ArrowArrayStream`. On success the caller owns the stream and must release it
 * via `out->release(out)` (or by handing it to an Arrow C Data Interface importer, which takes
 * ownership). The schema is present even for an empty result.
 *
 * # Safety
 * `db` a valid handle; `sql` a valid C string; `out` a valid, writable `ArrowArrayStream` slot that
 * does not already hold an un-released stream.
 */
imbh_error imbh_db_query_sql(struct imbh_db *db, const char *sql, struct ArrowArrayStream *out);

/**
 * Force-seal the mutable buffer into an immutable segment.
 *
 * # Safety
 * `db` must be a valid handle or null.
 */
imbh_error imbh_db_flush(struct imbh_db *db);

/**
 * Run one maintenance pass (seal + retention). Writes `*report` if non-null.
 *
 * # Safety
 * `db` a valid handle; `report` may be null.
 */
imbh_error imbh_db_maintain(struct imbh_db *db, struct imbh_maintenance_report *report);

/**
 * Compact small segments. Writes `*report` if non-null.
 *
 * # Safety
 * `db` a valid handle; `report` may be null.
 */
imbh_error imbh_db_compact(struct imbh_db *db, struct imbh_compaction_report *report);

/**
 * Fill `*out` with engine-wide statistics.
 *
 * # Safety
 * `db` a valid handle; `out` a valid writable slot.
 */
imbh_error imbh_db_stats(struct imbh_db *db, struct imbh_stats *out);

/**
 * Fill `*out` with statistics for a single `table`.
 *
 * # Safety
 * `db` a valid handle; `out` a valid writable slot.
 */
imbh_error imbh_db_table_stats(struct imbh_db *db,
                               enum imbh_table table,
                               struct imbh_table_stats *out);

/**
 * Take a consistent point-in-time snapshot of the sealed segments into `dir` (created if absent),
 * hard-linking where possible. Writes `*info` if non-null. The buffered (unsealed) rows are not
 * included — flush first for a fully-durable snapshot.
 *
 * # Safety
 * `db` a valid handle; `dir` a valid C string; `info` may be null.
 */
imbh_error imbh_db_snapshot(struct imbh_db *db, const char *dir, struct imbh_snapshot_info *info);

/**
 * The highest LSN fsync'd to the WAL. Writes `*lsn` (0 when nothing is durable yet — a real LSN is
 * always ≥ 1). This is the durability watermark `imbh_ingest_receipt.lsn` is compared against.
 *
 * # Safety
 * `db` a valid handle; `lsn` a valid, writable `uint64_t` slot.
 */
imbh_error imbh_db_durable_through(struct imbh_db *db,
                                   uint64_t *lsn);

/**
 * List the DB's sealed segments as an Arrow stream. Result columns: `relative_path` (Utf8),
 * `min_time_unix_nano`, `max_time_unix_nano`, `rows` (Int64).
 *
 * # Safety
 * `db` a valid handle; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_segments(struct imbh_db *db, struct ArrowArrayStream *out);

/**
 * List one table's on-disk segment files (absolute paths) as an Arrow stream. Result column: `path`
 * (Utf8).
 *
 * # Safety
 * `db` a valid handle; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_segment_files(struct imbh_db *db,
                                 enum imbh_table table,
                                 struct ArrowArrayStream *out);

/**
 * Export a table's rows over `[start, end)` (unix-nanos) as **Arrow-IPC stream bytes** — the fallback
 * transport for a consumer without a C Data Interface importer. Pass `start == 0 && end == 0` for the
 * whole time range. Writes the owned buffer to `*out`; release it with `imbh_bytes_free`.
 *
 * # Safety
 * `db` a valid handle; `out` a valid, writable `imbh_bytes` slot.
 */
imbh_error imbh_db_export(struct imbh_db *db,
                          enum imbh_table table,
                          int64_t start_unix_nanos,
                          int64_t end_unix_nanos,
                          struct imbh_bytes *out);

/**
 * Run SQL and return the result as **Arrow-IPC stream bytes** instead of a C Data Interface stream —
 * the fallback for a consumer that decodes IPC rather than importing the zero-copy stream. The schema
 * is always encoded (even for an empty result). Writes the owned buffer to `*out`; release it with
 * `imbh_bytes_free`.
 *
 * # Safety
 * `db` a valid handle; `sql` a valid C string; `out` a valid, writable `imbh_bytes` slot.
 */
imbh_error imbh_db_query_sql_ipc(struct imbh_db *db,
                                 const char *sql,
                                 struct imbh_bytes *out);

/**
 * All distinct attribute/label keys across the store → one column `name` (Utf8).
 *
 * # Safety
 * `db` a valid handle; `out` a valid, writable `ArrowArrayStream` slot that does not already hold an
 * un-released stream.
 */
imbh_error imbh_db_attr_names(struct imbh_db *db,
                              struct ArrowArrayStream *out);

/**
 * Distinct values for one attribute key → one column `value` (Utf8).
 *
 * # Safety
 * `db` a valid handle; `key` a valid C string; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_attr_values(struct imbh_db *db, const char *key, struct ArrowArrayStream *out);

/**
 * The metric catalog → columns `metric` (Utf8), `unit` (Utf8), `temporality` (Utf8, null when the
 * metric has none), `kind` (Utf8).
 *
 * # Safety
 * `db` a valid handle; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_metric_catalog(struct imbh_db *db, struct ArrowArrayStream *out);

/**
 * The distinct label sets carrying a metric → one column `labels` (Utf8), one canonical-JSON string
 * per series.
 *
 * # Safety
 * `db` a valid handle; `metric` a valid C string; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_metric_series(struct imbh_db *db,
                                 const char *metric,
                                 struct ArrowArrayStream *out);

/**
 * All exemplars recorded for a metric → columns `time` (Int64 ns), `value` (Float64), `trace_id`
 * (Utf8 hex, null when the exemplar carries none), `span_id` (Utf8 hex, null likewise), `attributes`
 * (Utf8 canonical JSON).
 *
 * # Safety
 * `db` a valid handle; `metric` a valid C string; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_metric_exemplars(struct imbh_db *db,
                                    const char *metric,
                                    struct ArrowArrayStream *out);

/**
 * Return the last error message on the calling thread as a NUL-terminated C string, or `NULL` if the
 * most recent `imbh_*` call on this thread succeeded (or none has run). The pointer is owned by the
 * binding and remains valid only until the next `imbh_*` call on the same thread.
 *
 * # Safety
 * The returned pointer must not be freed by the caller and must not be used across another `imbh_*`
 * call on the same thread.
 */
const char *imbh_last_error_message(void);

/**
 * Evaluate a **PromQL** query over `[start, end]` at `step` (all unix nanoseconds), streaming the
 * result as Arrow rows (`labels | timestamp | value`). The metric namespace is resolved from the
 * stored catalog first (query-name is the metric with dots→underscores, Prometheus convention), so a
 * PromQL name like `http_requests_total` matches a stored `http.requests.total`.
 *
 * # Safety
 * `db` a valid handle; `query` a valid C string; `out` a valid, writable `ArrowArrayStream` slot that
 * does not already hold an un-released stream.
 */
imbh_error imbh_db_query_promql(struct imbh_db *db,
                                const char *query,
                                int64_t start,
                                int64_t end,
                                int64_t step,
                                struct ArrowArrayStream *out);

/**
 * Evaluate a **LogQL** query. A bare stream selector (`{service="checkout"} |= "error"`) returns log
 * lines (Loki `streams`), capped at `limit` entries (or 1000 when `limit <= 0`); `step` is ignored on
 * this path. A range aggregation (`count_over_time(...)`) returns a metric series over `step` buckets
 * (Loki `matrix`), the same `labels | timestamp | value` shape as PromQL. Result columns therefore
 * depend on the query form, exactly as they do in Loki.
 *
 * # Safety
 * As `imbh_db_query_promql`.
 */
imbh_error imbh_db_query_logql(struct imbh_db *db,
                               const char *query,
                               int64_t start,
                               int64_t end,
                               int64_t step,
                               int64_t limit,
                               struct ArrowArrayStream *out);

/**
 * Evaluate a **TraceQL** spanset query over `[start, end]` (unix nanoseconds), streaming the matching
 * `trace_id | span_id` pairs as Arrow rows. Feed a matched `trace_id` to `imbh_db_get_trace` to pull
 * the full trace.
 *
 * # Safety
 * As `imbh_db_query_promql`.
 */
imbh_error imbh_db_query_traceql(struct imbh_db *db,
                                 const char *query,
                                 int64_t start,
                                 int64_t end,
                                 struct ArrowArrayStream *out);

/**
 * Fetch one trace's spans as Arrow (`traces().get_batches`) — the zero-copy counterpart to a trace
 * lookup, and the natural follow-up to a TraceQL match. `trace_id` is the 32-hex-character id;
 * anything else is [`imbh_error::InvalidArg`]. A trace that is simply absent yields an empty stream
 * (0 rows), not an error.
 *
 * # Safety
 * `db` a valid handle; `trace_id` a valid C string; `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_get_trace(struct imbh_db *db,
                             const char *trace_id,
                             struct ArrowArrayStream *out);

/**
 * Allocate an empty log-query builder. Never null. Free with `imbh_log_query_free`.
 */
struct imbh_log_query *imbh_log_query_new(void);

/**
 * Free a log-query builder. Passing null is a no-op.
 *
 * # Safety
 * `q` must be a builder from `imbh_log_query_new` and not already freed, or null.
 */
void imbh_log_query_free(struct imbh_log_query *q);

/**
 * Restrict to a service name.
 *
 * # Safety
 * `q` a valid builder; `service` a valid C string.
 */
imbh_error imbh_log_query_set_service(struct imbh_log_query *q, const char *service);

/**
 * Require severity ≥ `min` (OTel severity number 1..=24).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_log_query_set_min_severity(struct imbh_log_query *q, uint32_t min);

/**
 * Full-text `matches` filter over the log body.
 *
 * # Safety
 * `q` a valid builder; `text` a C string.
 */
imbh_error imbh_log_query_set_text(struct imbh_log_query *q, const char *text);

/**
 * Restrict to the half-open time window `[start, end)` in unix-nanos (`i64::MIN`/`MAX` = unbounded).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_log_query_set_range(struct imbh_log_query *q,
                                    int64_t start_unix_nanos,
                                    int64_t end_unix_nanos);

/**
 * Cap the number of returned rows (0 → builder default, 100).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_log_query_set_limit(struct imbh_log_query *q, uint64_t limit);

/**
 * Set the scan direction.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_log_query_set_direction(struct imbh_log_query *q, enum imbh_direction direction);

/**
 * Set the page cursor offset.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_log_query_set_offset(struct imbh_log_query *q, uint64_t offset);

/**
 * Add an `attribute == value` filter.
 *
 * # Safety
 * `q` a valid builder; `key`/`value` C strings.
 */
imbh_error imbh_log_query_add_attr_eq(struct imbh_log_query *q, const char *key, const char *value);

/**
 * Add an `attribute exists` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string.
 */
imbh_error imbh_log_query_add_attr_exists(struct imbh_log_query *q, const char *key);

/**
 * Add an `attribute matches value` (full-text) filter.
 *
 * # Safety
 * `q` a valid builder; C strings.
 */
imbh_error imbh_log_query_add_attr_matches(struct imbh_log_query *q,
                                           const char *key,
                                           const char *value);

/**
 * Add an `attribute regex value` filter.
 *
 * # Safety
 * `q` a valid builder; C strings.
 */
imbh_error imbh_log_query_add_attr_regex(struct imbh_log_query *q,
                                         const char *key,
                                         const char *value);

/**
 * Add an `attribute ∈ {values}` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string; `values`
 * an array of `n` C strings.
 */
imbh_error imbh_log_query_add_attr_in(struct imbh_log_query *q,
                                      const char *key,
                                      const char *const *values,
                                      uintptr_t n);

/**
 * Add an `attribute ∉ {values}` filter.
 *
 * # Safety
 * as `imbh_log_query_add_attr_in`.
 */
imbh_error imbh_log_query_add_attr_not_in(struct imbh_log_query *q,
                                          const char *key,
                                          const char *const *values,
                                          uintptr_t n);

/**
 * Add a numeric `attribute <op> value` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string.
 */
imbh_error imbh_log_query_add_attr_num(struct imbh_log_query *q,
                                       const char *key,
                                       enum imbh_num_op op,
                                       double value);

/**
 * Allocate a metric range-query builder for the given family. Never null. Set the metric name with
 * `imbh_metric_query_set_metric` before running. Free with `imbh_metric_query_free`.
 */
struct imbh_metric_query *imbh_metric_query_new(enum imbh_metric_table table);

/**
 * Free a metric-query builder. Passing null is a no-op.
 *
 * # Safety
 * `q` a builder from `imbh_metric_query_new`, not already freed, or null.
 */
void imbh_metric_query_free(struct imbh_metric_query *q);

/**
 * Set the metric name (required).
 *
 * # Safety
 * `q` a valid builder; `metric` a C string.
 */
imbh_error imbh_metric_query_set_metric(struct imbh_metric_query *q, const char *metric);

/**
 * Set the aggregation (absent → family default).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_query_set_aggregation(struct imbh_metric_query *q,
                                             enum imbh_aggregation aggregation);

/**
 * Add a group-by label.
 *
 * # Safety
 * `q` a valid builder; `label` a C string.
 */
imbh_error imbh_metric_query_add_group_by(struct imbh_metric_query *q, const char *label);

/**
 * Add a label selector `key <op> value`.
 *
 * # Safety
 * `q` a valid builder; `key`/`value` C strings.
 */
imbh_error imbh_metric_query_add_filter(struct imbh_metric_query *q,
                                        const char *key,
                                        enum imbh_label_op op,
                                        const char *value);

/**
 * Restrict to the half-open time window `[start, end)` in unix-nanos.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_query_set_range(struct imbh_metric_query *q,
                                       int64_t start_unix_nanos,
                                       int64_t end_unix_nanos);

/**
 * Set the range step in nanoseconds (absent → builder default, 60s).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_query_set_step_nanos(struct imbh_metric_query *q, int64_t step_nanos);

/**
 * Set the rate mode.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_query_set_rate(struct imbh_metric_query *q, enum imbh_rate_mode rate);

/**
 * Allocate an empty span-metrics (RED) query builder. Never null. Free with
 * `imbh_span_metrics_query_free`.
 */
struct imbh_span_metrics_query *imbh_span_metrics_query_new(void);

/**
 * Free a span-metrics query builder. Passing null is a no-op.
 *
 * # Safety
 * `q` a builder from `imbh_span_metrics_query_new`, not already freed, or null.
 */
void imbh_span_metrics_query_free(struct imbh_span_metrics_query *q);

/**
 * Restrict to a service.
 *
 * # Safety
 * `q` a valid builder; `service` a C string.
 */
imbh_error imbh_span_metrics_query_set_service(struct imbh_span_metrics_query *q,
                                               const char *service);

/**
 * Restrict to a span name.
 *
 * # Safety
 * `q` a valid builder; `name` a C string.
 */
imbh_error imbh_span_metrics_query_set_name(struct imbh_span_metrics_query *q, const char *name);

/**
 * Restrict to a span kind (SERVER / CLIENT / …).
 *
 * # Safety
 * `q` a valid builder; `kind` a C string.
 */
imbh_error imbh_span_metrics_query_set_kind(struct imbh_span_metrics_query *q, const char *kind);

/**
 * Restrict to a status (UNSET / OK / ERROR).
 *
 * # Safety
 * `q` a valid builder; `status` a C string.
 */
imbh_error imbh_span_metrics_query_set_status(struct imbh_span_metrics_query *q,
                                              const char *status);

/**
 * Add an `attribute == value` filter.
 *
 * # Safety
 * `q` a valid builder; `key`/`value` C strings.
 */
imbh_error imbh_span_metrics_query_add_attr_eq(struct imbh_span_metrics_query *q,
                                               const char *key,
                                               const char *value);

/**
 * Add a group-by label.
 *
 * # Safety
 * `q` a valid builder; `label` a C string.
 */
imbh_error imbh_span_metrics_query_add_group_by(struct imbh_span_metrics_query *q,
                                                const char *label);

/**
 * Restrict to the half-open time window `[start, end)` in unix-nanos.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_span_metrics_query_set_range(struct imbh_span_metrics_query *q,
                                             int64_t start_unix_nanos,
                                             int64_t end_unix_nanos);

/**
 * Set the bucket step in nanoseconds (absent → builder default, 60s).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_span_metrics_query_set_step_nanos(struct imbh_span_metrics_query *q,
                                                  int64_t step_nanos);

/**
 * Run a typed **log** query, exporting the matched rows into `*out` (Arrow stream) and filling
 * `*stats` if non-null. Result columns are the canonical `logs` projection.
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_log_query`; `out` a valid writable stream slot; `stats`
 * may be null.
 */
imbh_error imbh_db_logs_query(struct imbh_db *db,
                              const struct imbh_log_query *query,
                              struct ArrowArrayStream *out,
                              struct imbh_query_stats *stats);

/**
 * Run a typed **metric range** query. Result columns are `bucket`, one `g0..gN` per group-by, then
 * the value column `v`.
 *
 * # Safety
 * As `imbh_db_logs_query`, with an `imbh_metric_query`.
 */
imbh_error imbh_db_metrics_range(struct imbh_db *db,
                                 const struct imbh_metric_query *query,
                                 struct ArrowArrayStream *out,
                                 struct imbh_query_stats *stats);

/**
 * Run a typed **span-metrics (RED)** query. Result columns are `bucket`, one `g0..gN` per group-by,
 * then `calls, errors, p50, p95, p99`.
 *
 * # Safety
 * As `imbh_db_logs_query`, with an `imbh_span_metrics_query`.
 */
imbh_error imbh_db_traces_span_metrics(struct imbh_db *db,
                                       const struct imbh_span_metrics_query *query,
                                       struct ArrowArrayStream *out,
                                       struct imbh_query_stats *stats);

/**
 * Run an **instant** metric query — the last sample per series over the query's window, built with
 * the same `imbh_metric_query` builder as `imbh_db_metrics_range`. Result columns are the long-form
 * `labels` (Utf8 canonical JSON) | `timestamp` (Int64 ns) | `value` (Float64), one row per series.
 * (IMBH materializes the instant vector, so there is no `imbh_query_stats` for this entry point.)
 *
 * # Safety
 * As `imbh_db_metrics_range`, but with no `stats` out-param.
 */
imbh_error imbh_db_metrics_instant(struct imbh_db *db,
                                   const struct imbh_metric_query *query,
                                   struct ArrowArrayStream *out);

/**
 * Run a **log volume** query — per (step-bucket, label set) counts over the `imbh_log_query`'s
 * filter, the count-over-time histogram Loki's volume endpoint serves. `group_by`/`group_by_len` is
 * the label keys to break down by (pass null/0 for the ungrouped total). Result columns are
 * `bucket_time` (Int64 ns) | `labels` (Utf8 canonical JSON of the bucket's key/values, `{}` when
 * ungrouped) | `count` (Int64).
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_log_query`; `group_by` an array of `group_by_len` valid
 * C strings (or null iff `group_by_len == 0`); `out` a valid, writable `ArrowArrayStream` slot.
 */
imbh_error imbh_db_logs_volume(struct imbh_db *db,
                               const struct imbh_log_query *query,
                               uint64_t step_nanos,
                               const char *const *group_by,
                               uintptr_t group_by_len,
                               struct ArrowArrayStream *out);

/**
 * Run a **paged** log query: the same query as `imbh_db_logs_query`, resumed from row offset `after`
 * (pass 0 for the first page). Streams the page's rows as Arrow and, when non-null, writes the scan
 * `stats`, the `next_offset` to resume from, and `has_more` — true iff a full page came back (the
 * builder's `limit` rows). Paging is offset-based: reuse the *same* builder/filters across pages, and
 * stop when `has_more` is false. `has_more` is always false when the builder's `limit` is 0 (the
 * engine's default page size is applied but not reported back), mirroring the Go binding.
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_log_query`; `out` a valid, writable `ArrowArrayStream`
 * slot; `stats`/`next_offset`/`has_more` may each be null.
 */
imbh_error imbh_db_logs_page(struct imbh_db *db,
                             const struct imbh_log_query *query,
                             uint64_t after,
                             struct ArrowArrayStream *out,
                             struct imbh_query_stats *stats,
                             uint64_t *next_offset,
                             bool *has_more);

/**
 * Count the log rows matching a query's **filters** — `limit`, `offset`, and `direction` are ignored
 * (it is `SELECT count(*)` over the same `WHERE`). The total a paged UI shows next to the current
 * page. Writes the count to `*count`.
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_log_query`; `count` a valid, writable `uint64_t` slot.
 */
imbh_error imbh_db_logs_count(struct imbh_db *db,
                              const struct imbh_log_query *query,
                              uint64_t *count);

/**
 * Allocate an empty trace-search builder. Never null. Free with `imbh_trace_query_free`.
 */
struct imbh_trace_query *imbh_trace_query_new(void);

/**
 * Free a trace-search builder. Passing null is a no-op.
 *
 * # Safety
 * `q` a builder from `imbh_trace_query_new`, not already freed, or null.
 */
void imbh_trace_query_free(struct imbh_trace_query *q);

/**
 * Restrict to a root-span service name.
 *
 * # Safety
 * `q` a valid builder; `service` a C string.
 */
imbh_error imbh_trace_query_set_service(struct imbh_trace_query *q, const char *service);

/**
 * Restrict to a span name.
 *
 * # Safety
 * `q` a valid builder; `name` a C string.
 */
imbh_error imbh_trace_query_set_name(struct imbh_trace_query *q, const char *name);

/**
 * Full-text `matches` filter over the span name.
 *
 * # Safety
 * `q` a valid builder; `text` a C string.
 */
imbh_error imbh_trace_query_set_text(struct imbh_trace_query *q, const char *text);

/**
 * Restrict to a span status (`UNSET` / `OK` / `ERROR`).
 *
 * # Safety
 * `q` a valid builder; `status` a C string.
 */
imbh_error imbh_trace_query_set_status(struct imbh_trace_query *q, const char *status);

/**
 * Restrict to a span kind (`SERVER` / `CLIENT` / …).
 *
 * # Safety
 * `q` a valid builder; `kind` a C string.
 */
imbh_error imbh_trace_query_set_kind(struct imbh_trace_query *q, const char *kind);

/**
 * Require the trace's root-span duration ≥ `min_duration_nanos`.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_trace_query_set_min_duration_nanos(struct imbh_trace_query *q,
                                                   uint64_t min_duration_nanos);

/**
 * Require the trace's root-span duration ≤ `max_duration_nanos`.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_trace_query_set_max_duration_nanos(struct imbh_trace_query *q,
                                                   uint64_t max_duration_nanos);

/**
 * Restrict to the half-open time window `[start, end)` in unix-nanos.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_trace_query_set_range(struct imbh_trace_query *q,
                                      int64_t start_unix_nanos,
                                      int64_t end_unix_nanos);

/**
 * Cap the number of returned traces (0 → builder default, 20).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_trace_query_set_limit(struct imbh_trace_query *q, uint64_t limit);

/**
 * Add a span-`attribute == value` filter.
 *
 * # Safety
 * `q` a valid builder; `key`/`value` C strings.
 */
imbh_error imbh_trace_query_add_attr_eq(struct imbh_trace_query *q,
                                        const char *key,
                                        const char *value);

/**
 * Add a span-`attribute exists` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string.
 */
imbh_error imbh_trace_query_add_attr_exists(struct imbh_trace_query *q, const char *key);

/**
 * Add a span-`attribute matches value` (full-text) filter.
 *
 * # Safety
 * `q` a valid builder; C strings.
 */
imbh_error imbh_trace_query_add_attr_matches(struct imbh_trace_query *q,
                                             const char *key,
                                             const char *value);

/**
 * Add a span-`attribute regex value` filter.
 *
 * # Safety
 * `q` a valid builder; C strings.
 */
imbh_error imbh_trace_query_add_attr_regex(struct imbh_trace_query *q,
                                           const char *key,
                                           const char *value);

/**
 * Add a span-`attribute ∈ {values}` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string; `values` an array of `n` C strings.
 */
imbh_error imbh_trace_query_add_attr_in(struct imbh_trace_query *q,
                                        const char *key,
                                        const char *const *values,
                                        uintptr_t n);

/**
 * Add a span-`attribute ∉ {values}` filter.
 *
 * # Safety
 * as `imbh_trace_query_add_attr_in`.
 */
imbh_error imbh_trace_query_add_attr_not_in(struct imbh_trace_query *q,
                                            const char *key,
                                            const char *const *values,
                                            uintptr_t n);

/**
 * Add a numeric span-`attribute <op> value` filter.
 *
 * # Safety
 * `q` a valid builder; `key` a C string.
 */
imbh_error imbh_trace_query_add_attr_num(struct imbh_trace_query *q,
                                         const char *key,
                                         enum imbh_num_op op,
                                         double value);

/**
 * Run a **trace search**. Result columns are `trace_id` (Utf8 hex), `root_service`, `root_name`
 * (nullable), `start_time`, `duration_ns`, `span_count` (Int64), `error` (Boolean) — one row per
 * matching trace summary, newest first.
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_trace_query`; `out` a valid, writable `ArrowArrayStream`
 * slot.
 */
imbh_error imbh_db_traces_search(struct imbh_db *db,
                                 const struct imbh_trace_query *query,
                                 struct ArrowArrayStream *out);

/**
 * Allocate a metric-points (raw samples) builder for the given family. Never null. Set the metric
 * name with `imbh_metric_points_query_set_metric` before running. Free with
 * `imbh_metric_points_query_free`.
 */
struct imbh_metric_points_query *imbh_metric_points_query_new(enum imbh_metric_point_kind kind);

/**
 * Free a metric-points builder. Passing null is a no-op.
 *
 * # Safety
 * `q` a builder from `imbh_metric_points_query_new`, not already freed, or null.
 */
void imbh_metric_points_query_free(struct imbh_metric_points_query *q);

/**
 * Set the metric name (required).
 *
 * # Safety
 * `q` a valid builder; `metric` a C string.
 */
imbh_error imbh_metric_points_query_set_metric(struct imbh_metric_points_query *q,
                                               const char *metric);

/**
 * Add an `attribute == value` equality filter (AND-ed).
 *
 * # Safety
 * `q` a valid builder; `key`/`value` C strings.
 */
imbh_error imbh_metric_points_query_add_filter(struct imbh_metric_points_query *q,
                                               const char *key,
                                               const char *value);

/**
 * Restrict to the half-open time window `[start, end)` in unix-nanos.
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_points_query_set_range(struct imbh_metric_points_query *q,
                                              int64_t start_unix_nanos,
                                              int64_t end_unix_nanos);

/**
 * Cap the number of returned points (0 → builder default, 100).
 *
 * # Safety
 * `q` a valid builder.
 */
imbh_error imbh_metric_points_query_set_limit(struct imbh_metric_points_query *q, uint64_t limit);

/**
 * Run a **metric points** query — the raw, unaggregated samples for a metric (the counterpart to the
 * aggregated `imbh_db_metrics_range`). Column layout depends on the family: scalar (gauge/sum) rows
 * carry a `value`; histogram rows carry `explicit_bounds`/`bucket_counts` (see IMBH's
 * `MetricPointsQuery` docs).
 *
 * # Safety
 * `db` a valid handle; `query` a valid `imbh_metric_points_query`; `out` a valid, writable
 * `ArrowArrayStream` slot.
 */
imbh_error imbh_db_metrics_points(struct imbh_db *db,
                                  const struct imbh_metric_points_query *query,
                                  struct ArrowArrayStream *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IMBH_H */
